### ISSUE TITLE
Generate snapshot definition from differential

### ISSUE THREAD

**Issue by simonvadee** [arkhn/pyrog#135]

**Comment by elsiehoffet-94** [comment]
We want to support an operation which generates a snapshot from a differential StructureDefinition, as described by FHIR [documentation](http://hl7.org/fhir/OperationDefinition/StructureDefinition-snapshot). 

This operation is supported by Hapi FHIR. We could use a **temporary** route to create a StructureDefinition [on HAPI Fhir](http://hapi.fhir.org/resource?serverId=home_r4&pretty=true&resource=StructureDefinition) from a differential, and then use the [$snapshot operation](http://hapi.fhir.org/baseR4/StructureDefinition/619087/$snapshot) to convert it to a snapshot.
