### ISSUE TITLE
Dialog box for adding parsing scripts' code

### ISSUE THREAD

**Issue by alexisthual** [arkhn/pyrog#17]
- [ ] visualisation dialog box so as to check current chosen parsing script
- [ ] add plus button for adding new parsing script to the distant repo/folder

`./src/application/components/jsonViewer.tsx` is probably a good source to start a new component.
Moreover, `./src/application/views/main.tsx` uses `JsonViewer` in a blueprintjs `Dialog` box and gives an example to start from.

**Comment by LaRiffle** [comment]
I'm closing this one because it's a bit out of date
In addition, cleaning scripts can currently by selected as part of the pyrog interface
