### ISSUE TITLE
Slicing is not handled

### ISSUE THREAD

**Issue by elsiehoffet-94** [arkhn/pyrog#182]
Some things to fix before the demo:

- some parsing issues with arrays attributes in profiles (for ex: in heartrate, see screenshot) 
![Capture d’écran 2020-02-24 à 18 13 22](https://user-images.githubusercontent.com/56258130/75175899-7c627f80-5733-11ea-9a40-1360824827c2.png)

**Comment by simonvadee** [comment]
StructureDefinition handling is becoming a huge mess because the caching in pyrog-server and the display in pyrog-client are completely uncorrelated. Maybe (?) we should use the same types in the server and in the client (eg: `Node` from pyrog-client)
