### ISSUE TITLE
Impossibility to create a  static resource 

### ISSUE THREAD

**Issue by elsiehoffet-94** [arkhn/pyrog#191]
Problem: 
we want to create one (or very few) instances of ResearchStudy which has only static values (identifier.value = SHIVA, status= active) and not indexed on a table (i.e. does not have a primary key).

It needs to be discussed: 
- Do we want to be able to create a resource that is not indexed on a primary key? It could be made by selecting a "this resource is not indexed on a table in the db" button
- Should it be made outside of the fhir resource tree ?

**Comment by Jasopaum** [comment]
So if I understand well, the source DB isn’t needed at all in this case, only static values will be used, am I wrong?

**Comment by elsiehoffet-94** [comment]
Yes that is correct.
