### ISSUE TITLE
Add SQL scripts

### ISSUE THREAD

**Issue by KouakouVerde** [arkhn/pyrog#28]
A nice feature asked by several users would be to be able to copy-paste a piece of SQL code (Oracle SQL since it is the only one used in the hospitals) into the interface.
We would then parse it in order to detect the columns selected by the script, and then propose find a way to present matching possibilites between the parsed columns from the script and the FHIR attributes.

**Comment by alexis-thual** [comment]
I believe this is a WIP in #45 :slightly_smiling_face:

**Comment by tenrol** [comment]
> I believe this is a WIP in #45 🙂

Yes you are right :-)
