### ISSUE TITLE
Click and refresh bugs in pyrog-front

### ISSUE THREAD

**Issue by elsiehoffet-94** [arkhn/pyrog#376]
Some issues with pyrog-front:
- The main page with all the sources takes quite a long time to load
- Clicking on a source sometimes does not work, the page has to be refreshed
- Refreshing on a ressource page will lead to a bug (dark page)

**Comment by nriss** [comment]
A precision about the second point, the bug about the source that become not clickable is reproducible by:
* Clicking on a source (work the first time)
* Clicking on "< Sources" return button
* Clicking again on a source

When we refresh the page, the source cards become clickable again

**Comment by triou-arkhn** [comment]
I think we should open a separate issue about the performance issue
