### ISSUE TITLE
(select a resource) select box

### ISSUE THREAD

**Issue by nriss** [arkhn/pyrog#404]
## Description

We can only write "CodeSystem" or any substring about it 

## Reproduction

1. Go on staging, on CroixRouge EtablissementFictif
2. Click on (Select a resource)
3. Try to type other thing than a substring of "CodeSystem"

It is the same for Resah - Mimic, we can only type PlanDefinition

## Expectation
We can write anything

## Environment

Staging

**Comment by nriss** [comment]
The bug doesn't appear on every source, it is the case for EtablissementFictif but not for osiris

**Comment by tevariou** [comment]
I can't reproduce this. Is it fixed @nriss ?

**Comment by nriss** [comment]
This problem remains on my computer in staging, on the source EtablissementFictif on chrome & safari

**Comment by tevariou** [comment]
@nriss Can you try again and tell me if everything's ok ? If so, I will close this issue.

**Comment by nriss** [comment]
It seems resolved
