### ISSUE TITLE
Table preview is empty and imposes to reload database schema

### ISSUE THREAD

**Issue by nriss** [arkhn/pyrog#408]
## Description
Table preview appears empty

## Reproduction

1. Go on any source on staging where the table schema have not been updated
2. See the empty table.

## Expectation

Show the table preview

## Screenshots

![image](https://user-images.githubusercontent.com/48218773/95055400-83069b80-06f3-11eb-9814-b0f6588748e1.png)

## Environment

On staging (EtablissementFictif, osiris, demo-sophie...)
The bug is corrected after updating the database credentials (update the table schema) and refreshing the page

## Additional context

Request result : 
`"fields":[],"rows":[[],[]]}`

Request URL : 
`https://staging.arkhn.com/pagai/explore/ck987j7hb00004upe4crr3b8t/Analysis`

**Comment by nriss** [comment]
same bug as https://github.com/arkhn/pagai/issues/56

**Comment by nriss** [comment]
Adding High priority label because reader users cannot see the table, cannot update the table schema, cannot make any previews

**Comment by nriss** [comment]
Tested on multiple sources on staging, it seems to work !
Great job, thanks 🙂
I will try again tomorrow morning to be sure 😌

**Comment by Jasopaum** [comment]
Please reopen if it happens again after pagai 0.1.1
