### ISSUE TITLE
[Data catalog] Change READER permissions

### ISSUE THREAD

**Issue by nriss** [arkhn/pyrog#414]
## Problem

The goal is there to get a first version of a data catalog

## Description

When a resource is selected, READER users should only see the mapped attributes
FHIR attributes that are not mapped shouldn't be displayed

## Next steps

The next steps will consist on generating tables and schemes

## Roles
- visualiser: see the mapped attributes + comments
- validator: see the mapped attributes (+ unmapped ?), the comments and can validate each attribute
- writer: can see mapped/unmapped attributes and can change the mapping
- administrator: can do anything

**Comment by LaRiffle** [comment]
Can we keep the comments visible in this view?

**Comment by nriss** [comment]
The goal of the reader user is also to validate the mapping. So I think we have to keep the comments.

If we don't want to keep the comments for the data catalog, I think we have to create a new kind of user "visualiser". In this, case, the difference users would be: 
* visualiser: can only see the mapped attributes
* validator: can see the mapped attributes (+ unmapped ?), the comments and can validate each attribute
* writer: can see mapped/unmapped attributes and can change the mapping
* administrator : can do anything

**Comment by LaRiffle** [comment]
yeah exactly, my point was to say: the visualiser might want to see the comments to learn more about a given attribute (comments might contain important information about how it was mapped and potential limit of a mapping)

**Comment by nriss** [comment]
I agree 🙂

Finally, the roles are:
visualiser: see the mapped attributes + comments
validator: see the mapped attributes (+ unmapped ?), the comments and can validate each attribute
writer: can see mapped/unmapped attributes and can change the mapping
administrator : can do anything
