### ISSUE TITLE
Fail to add a condition on an attribute

### ISSUE THREAD

**Issue by Peltier10** [arkhn/pyrog#417]
## Description

Fail to add a condition on an attribute.

## Reproduction

1. On Staging > demo_sophie > Observation (Act realised by Pharmacist) > Primary key : Table = chartevents | Column = row_id
2. The attribute concerned by the bug : performer > display
3. Attribute input > Table : caregivers | Column : description
4. Add join between chartevents and caregivers on cgid
5. Add condition : Action = INCLUDE | Column = caregivers>description | Relation = "==" | Value = Pharmacist.
6. Try to see the result within clicking on the flame : nothing appears.

## Expectation

See chartevents with only rows of events made by caregivers that have description = Pharmacist.

## Additional context

When i'm looking for the error in the Inspecteur Web > Réseau, i have : "400 Bad Request", Answer : " error: "'NoneType' object has no attribute 'strip'" "
I had a filter on the resource and tried again the mapping for performer > display but i get the same error.
And it is impossible to delete the condition.

> Traceback (most recent call last): File "./extractor/src/main.py", line 79, in extract analysis = analyzer.fetch_analysis(resource_id) File "./analyzer/src/analyze/analyzer.py", line 40, in fetch_analysis return self.analyze(resource_mapping) File "./analyzer/src/analyze/analyzer.py", line 76, in analyze self.analyze_mapping(resource_mapping) File "./analyzer/src/analyze/analyzer.py", line 103, in analyze_mapping self.analyze_attribute(attribute_mapping) File "./analyzer/src/analyze/analyzer.py", line 140, in analyze_attribute self.analyze_input_group(mapping_group, attribute) File "./analyzer/src/analyze/analyzer.py", line 188, in analyze_input_group self._cur_analysis.primary_key_column.owner, File "./analyzer/src/analyze/sql_column.py", line 16, in **init** self.table = table.strip() AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by Jasopaum** [comment]
Should be solved by https://github.com/arkhn/fhir-river/pull/135
