### ISSUE TITLE
Mapped attribute don't appear on pyrog

### ISSUE THREAD

**Issue by nriss** [arkhn/pyrog#452]
## Description

When we map attributes on pyrog, they don't appear sometimes

## Reproduction

Difficult to reproduce because it happens sometime.
Try to map a test source (organization.identifier for example)

## Screenshots

![image](https://user-images.githubusercontent.com/48218773/99781371-12d39e00-2b18-11eb-94e0-b5f96e8458cd.png)

## Environment

Staging, after mapping identifiers

## Priority

1) It causes that we cannot verify our mapping so it induces lots of errors
2) Moreover, it induces lot of  waste of time if we have to refresh cache to verify everything

**Comment by Jasopaum** [comment]
I think this can be closed, feel free to re-open if needed
