### ISSUE TITLE
Attributes is duplicated in preview

### ISSUE THREAD

**Issue by nriss** [arkhn/pyrog#487]
## Description

When doing a preview of Condition - TPE, the identifier attribute is duplicated

## Reproduction

1. make a preview of dev or staging > source osiris - synthetic in dev > resource Condition - Tumor Pathology Event (TPE)
2. . See error in attribute, summary.coding, ...

## Expectation

These attributes must be completed only once

## Screenshots

![image](https://user-images.githubusercontent.com/48218773/105193694-0c25cf00-5b39-11eb-9982-4a5fe36e5e0f.png)

## Environment

dev or staging

Generated resource:

`[
    {
        "code": {
            "coding": [
                {
                    "system": "http://www.nlm.nih.gov/research/umls",
                    "code": "C0677930"
                },
                {
                    "system": "http://www.nlm.nih.gov/research/umls",
                    "code": "C0677930"
                }
            ]
        },
        "evidence": [
            {
                "detail": [
                    {
                        "identifier": {
                            "system": "http://terminology.arkhn.org/a3254504-da57-400d-bddc-b38ebd860fcd",
                            "value": "synthetic_biologicalsample_Synthetic_02_1"
                        },
                        "type": "Specimen"
                    },
                    {
                        "identifier": {
                            "system": "http://terminology.arkhn.org/a3254504-da57-400d-bddc-b38ebd860fcd",
                            "value": "synthetic_biologicalsample_Synthetic_02_4"
                        },
                        "type": "Specimen"
                    }
                ]
            },
            {
                "detail": [
                    {
                        "identifier": {
                            "system": "http://terminology.arkhn.org/a3254504-da57-400d-bddc-b38ebd860fcd",
                            "value": "synthetic_biologicalsample_Synthetic_02_1"
                        },
                        "type": "Specimen"
                    },
                    {
                        "identifier": {
                            "system": "http://terminology.arkhn.org/a3254504-da57-400d-bddc-b38ebd860fcd",
                            "value": "synthetic_biologicalsample_Synthetic_02_4"
                        },
                        "type": "Specimen"
                    }
                ]
            }
        ],
        "stage": [
            {
                "summary": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/sid/ICD-O-3",
                            "code": "ICDO3 :8144/3"
                        },
                        {
                            "system": "http://hl7.org/fhir/sid/ICD-O-3",
                            "code": "ICDO3 :8144/3"
                        }
                    ],
                    "text": "Morphology code"
                },
                "type": {
                    "coding": [
                        {
                            "code": "116676008",
                            "system": "http://www.nlm.nih.gov/research/umls",
                            "display": "Morphology"
                        }
                    ]
                }
            },
            {
                "summary": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/sid/ICD-O-3",
                            "code": "ICDO3 :8144/3"
                        },
                        {
                            "system": "http://hl7.org/fhir/sid/ICD-O-3",
                            "code": "ICDO3 :8144/3"
                        }
                    ],
                    "text": "Morphology code"
                },
                "type": {
                    "coding": [
                        {
                            "code": "116676008",
                            "system": "http://www.nlm.nih.gov/research/umls",
                            "display": "Morphology"
                        }
                    ]
                }
            },
            {
                "type": {
                    "coding": [
                        {
                            "code": "20228-3",
                            "system": "http://loinc.org",
                            "display": "Laterality"
                        }
                    ]
                },
                "summary": {
                    "coding": [
                        {
                            "code": "C2939193",
                            "system": "http://www.nlm.nih.gov/research/umls"
                        },
                        {
                            "code": "C2939193",
                            "system": "http://www.nlm.nih.gov/research/umls"
                        }
                    ],
                    "text": "Laterality"
                }
            },
            {
                "type": {
                    "coding": [
                        {
                            "code": "20228-3",
                            "system": "http://loinc.org",
                            "display": "Laterality"
                        }
                    ]
                },
                "summary": {
                    "coding": [
                        {
                            "code": "C2939193",
                            "system": "http://www.nlm.nih.gov/research/umls"
                        },
                        {
                            "code": "C2939193",
                            "system": "http://www.nlm.nih.gov/research/umls"
                        }
                    ],
                    "text": "Laterality"
                }
            }
        ],
        "subject": {
            "identifier": {
                "system": "http://terminology.arkhn.org/33a396fc-60e7-468e-a238-3f759fdadeef",
                "value": "synthetic_patient_Synthetic_02"
            },
            "type": "Patient"
        },
        "onsetDateTime": "2015-03-25",
        "abatementDateTime": "2015-09-29",
        "bodySite": [
            {
                "coding": [
                    {
                        "code": "C18.6",
                        "system": "http://hl7.org/fhir/sid/ICD-O-3"
                    },
                    {
                        "code": "C18.6",
                        "system": "http://hl7.org/fhir/sid/ICD-O-3"
                    }
                ],
                "text": "Topography code"
            },
            {
                "coding": [
                    {
                        "code": "C18.6",
                        "system": "http://hl7.org/fhir/sid/ICD-O-3"
                    },
                    {
                        "code": "C18.6",
                        "system": "http://hl7.org/fhir/sid/ICD-O-3"
                    }
                ],
                "text": "Topography code"
            }
        ],
        "recordedDate": "2015-03-25",
        "identifier": [
            {
                "system": "http://terminology.arkhn.org/90cc97dd-df89-400a-be9c-557b0fee96dd",
                "value": "synthetic_tumorpathologyevent_Synthetic_02_1"
            },
            {
                "system": "http://terminology.arkhn.org/90cc97dd-df89-400a-be9c-557b0fee96dd",
                "value": "synthetic_tumorpathologyevent_Synthetic_02_1"
            }
        ],
        "id": "21d82d94-0d0d-40d3-b722-c4aaacebd314",
        "resourceType": "Condition",
        "meta": {
            "lastUpdated": "2021-01-20T16:01:07Z",
            "tag": [
                {
                    "system": "http://terminology.arkhn.org/CodeSystem/source",
                    "code": "ckdreijp80006dupjto75nhrh"
                },
                {
                    "system": "http://terminology.arkhn.org/CodeSystem/resource",
                    "code": "ck9485atx07186opepzspxhap"
                }
            ]
        }
    }
]`

**Comment by Jasopaum** [comment]
Should be fixed by https://github.com/arkhn/fhir-river/pull/234
