### ISSUE TITLE
FHIR validation and prevent some errors in River

### ISSUE THREAD

**Issue by MiskoG** [arkhn/pyrog#528]
### Context

Very open issue as I don't have all the details here, and would be very interested to hear from you @nriss @elsiehoffet-94 @simonvadee !

It seems that we have implemented a FHIR syntax checker in Pyrog, in order for the user to see if his mapping to FHIR is correct. But we can still have errors in River, triggered by HAPI, due to unvalid FHIR instances trying to be created.

So my wonder is : how can we avoid those errors before running River ?

Some ideas could be the following ones =>

➡️  First, having a syntax-checker in Pyrog perfectly in sync with HAPI specifications. This is a good first step, but I guess that this is not enough as in Pyrog we can only test the syntax on 10 ressources.

➡️  We could also run some tests on the source data, for example checking that primary keys are not null and unique, etc.. We can do this at multiple stages of the stack. This could be done within the datalake for instance, as it is [a core feature of DBT](https://docs.getdbt.com/docs/building-a-dbt-project/tests).

➡️  Maybe we should also make River more flexible, because maybe that in some situations we don't want the FHIR instance generation to fail (it's okay for example if an attribute is empty in the worst case).

**Comment by simonvadee** [comment]
> ➡️ First, having a syntax-checker in Pyrog perfectly in sync with HAPI specifications. This is a good first step, but I guess that this is not enough as in Pyrog we can only test the syntax on 10 ressources.

💯% agreed, we should have a "fhir validator" endpoint in river api in sync with HAPI, and it's not very complicated to implement.

> ➡️ We could also run some tests on the source data, for example checking that primary keys are not null and unique, etc.. We can do this at multiple stages of the stack. This could be done within the datalake for instance, as it is a core feature of DBT.

I don't know if that would be really helpful, to me this is more a part of the exploration phase rather than validation. We could have a few sanity checks before the extraction phase though.

> ➡️ Maybe we should also make River more flexible, because maybe that in some situations we don't want the FHIR instance generation to fail (it's okay for example if an attribute is empty in the worst case).

not sure I understand, do you want to disable validation when loading the FHIR objects ?

**Comment by nriss** [comment]
A FHIR validator is really a must have according to me!

I think that a solution with few development would be to use the [$validate](https://www.hl7.org/fhir/resource-operation-validate.html) operation on hapi when making a preview

This operation also allow to validate against a profile, so it looks like a good solution and I think it will show some info about the validation errors

**Comment by MiskoG** [comment]
Thanks for your insights ! So I guess we agree on the first solution (I will create a separate issue for that, and will rename this current issue to be more general) ie having a FHIR validator in Pyrog, up-to-date with HAPI specs.

About my 2nd proposal (having data-sanity checks somewhere in the stack) : actually I'm trying to find a way to be more bullet-proof in River, keeping in mind that even with a great FHIR validator in Pyrog, we can only test 10 instances so there may be surprises.
@simonvadee @nriss @elsiehoffet-94 If you have recent examples of such River fails that would be interesting to discuss here, please feel free it will make the conversation more concrete 🙂 

> Maybe we should also make River more flexible, because maybe that in some situations we don't want the FHIR instance generation to fail (it's okay for example if an attribute is empty in the worst case).

Yeah you are both right, I didn't realize this meant in fact not being FHIR anymore.. 🙈 So let's forget it !
