### ISSUE TITLE
Better handling the code/display mapping

### ISSUE THREAD

**Issue by MiskoG** [arkhn/pyrog#530]
💡 Another issue (raised by @lnmylos) I suggest we discuss here. 

While mapping a FHIR ressource in Pyrog, it seems that the operations are often facing the situation where they need to map some source data to some ValueSet. 

For example, while creating an [Observation](https://www.hl7.org/fhir/observation.html) ressource you may want to fill the category attribute. FHIR suggests to use the [observation-category](https://www.hl7.org/fhir/valueset-observation-category.html) value set, which consists of a code (`social-history`), a display (`Social History`) and even a full definition (`Social History Observations define the patient's occupational, personal (e.g., lifestyle), social, familial, and environmental history and health risk factors that may impact the patient's health.`).

If I interpret our discussion correctly @lnmylos, I think we should discuss the following things :

- For mapping some attribute to a ValueSet (for example our Observation.category) - which practice do we recommand : only filling codes ? codes and displays ? every information available in the ValueSet (codes, displays and definitions) ?

- If the best practice consists of using more than one field of the ValueSet - let's say we wanna take into the FHIR attribute the code and display - is there any room in Pyrog to make things easier for the user ? Maybe taking more advantage of the ConceptMap feature (for example by linking a string to a whole ValueSet element, rather than to a string representing the code or the display) ?

@lnmylos Feel free to add some thoughts here
@nriss @Peltier10 @elsiehoffet-94 @tevariou Would love to hear from you on this one if you have any feedbacks and ideas !

**Comment by nriss** [comment]
You can also check these issues:

https://github.com/arkhn/pyrog/issues/424
https://github.com/arkhn/pyrog/issues/496


According to some discussion with @tevariou, we are not using ConceptMap on the correct way, we should use cleaning scripts to map concepts.
In the FHIR standard, ConceptMap is not a tool, it is just a resource to save mapping between terminologies, I think we should only use cleaning scripts to make changes during the ETL.

**Comment by lnmylos** [comment]
Exactly #496

**Comment by MiskoG** [comment]
I close this issue as it's completely what you suggest @nriss in https://github.com/arkhn/pyrog/issues/424 and #496
