### ISSUE TITLE
FHIR ressources json link is dead

### ISSUE THREAD

**Issue by strayMat** [arkhn/pyrog#55]
Trying to make the server works, I suppose that I need FHIR specifications as specified in the [README](https://github.com/arkhn/pyrog/tree/master/server):

> FHIR resources json descriptions are needed for this server to run successfully

But I am not able to dowload them from your link (seems dead): 

`wget https://arkhn.org/pyrog_dev_static.zip`
returns `404 error: Not Found`

**Comment by LaRiffle** [comment]
Hey! This should be fixed by now :)
